### ISSUE TITLE
Implement `yarn watch` for Improved Development Workflow

### ISSUE THREAD

**Issue by devcodes9** [shipmnts/editor-hub#11]
## Is your feature request related to a problem? Please describe.
Currently, developers need to manually rebuild the project after making changes, which slows down the development process. Implementing a `watch` command would automate this process, improving developer productivity.

## Describe the solution you'd like
Add a `watch` script to the `package.json` that uses Webpack (or another appropriate tool) to watch for file changes and automatically rebuild the project. This should:

1. Watch for changes in source files
2. Automatically rebuild the project when changes are detected
3. Provide clear console output about the rebuild process

## Implementation details

1. Add a new script to `package.json` for the watch command
2. Configure Webpack (or another build tool) to watch for file changes

# Additional context
Implementing a watch command will significantly improve the development experience by automating the rebuild process. This is especially useful for larger projects or when making frequent changes.

## Possible challenges
1. Ensuring that all necessary files are included in the watch process
2. Optimizing the watch process for performance, especially for larger projects

## Acceptance Criteria
- [ ] A new `yarn watch` command is available
- [ ] The command successfully watches for file changes in the root directory
- [ ] Changes to source files trigger an automatic rebuild
- [ ] The console provides clear output about the rebuild process
- [ ] Documentation is updated to include usage instructions for the new command

**Comment by RameezIbrahimOfficial** [comment]
Hi @devcodes9 
Can you Please Assign this task to me. 
I will do it.
