### ISSUE TITLE
Add Theme Switching Prop for Easy Customization

### ISSUE THREAD

**Issue by devdcodes9** [shipmnts/editor-hub#4]
## Is your feature request related to a problem? Please describe.
Currently, the Editor Hub uses a fixed theme (snow) for the Quill editor. Users who want to switch between themes (e.g., from snow to bubble) need to modify the code directly, which is inconvenient and not flexible for different use cases.

## Describe the solution you'd like
We should add a new prop called `theme` to the `RichTextEditorWrapper` component. This prop would allow users to easily switch between the "snow" and "bubble" themes (and potentially other themes in the future) without modifying the component's internal code.

The implementation would involve:
1. Adding a `theme` prop to the `RichTextEditorWrapper` component.
2. Modifying the Quill initialization to use the provided theme.
3. Updating the documentation to reflect this new customization option.

## Describe alternatives you've considered
1. Using "tooltip" directly as the theme name as it is more descriptive of bubble theme's functionality. Keeping snow theme as default.

## Additional context
https://quilljs.com/docs/customization/themes
This feature would greatly enhance the customizability of the Editor Hub, allowing users to easily switch between themes based on their project requirements or user preferences. It aligns with the project's goal of being a powerful and customizable rich text editor component for React applications.

**Comment by aarifkhan7** [comment]
Hey

I'm a beginner interested in contributing to open source, and this issue seems like a good starting point for me. Could you please assign it to me?

Thanks!

**Comment by devdcodes9** [comment]
@aarifkhan7 Assigned to you! Please make sure to open up a PR under 48 hrs for this issue. Happy Coding :)

> Hey
> 
> I'm a beginner interested in contributing to open source, and this issue seems like a good starting point for me. Could you please assign it to me?
> 
> Thanks!

**Comment by devdcodes9** [comment]
@aarifkhan7 Are you still working on this? any updates? are you stuck somewhere?

**Comment by aarifkhan7** [comment]
Hey, I am working on it, will try to push the fix today.

**Comment by devdcodes9** [comment]
@aarifkhan7 Are you still working on this?

**Comment by aarifkhan7** [comment]
Hey @devdcodes9, I am busy with another task right now, and won't be able to contribute to this issue, I apologize for the inconvenience.
